### ISSUE TITLE
Possible bug in candid subtying

### ISSUE THREAD

**Issue by crusso** [dfinity/candid#319]
https://github.com/dfinity/candid/blob/eca0d281a73401ecadcb9f00f847dfdf49ff83a1/rust/candid/src/types/subtype.rs#L54

Is this correct?

Is `opt null <: null`? If not (as I would expect from vanilla subtyping, then this will return false when `t2` is  null, won't it? But the message suggests `t2 == null` is allowed.

Am I confused?

**Comment by nomeata** [comment]
I wouldn’t be surprised if we have odd cases around `null`, because it is a bit like `opt empty`, but not in all respects…

But based on https://github.com/dfinity/candid/blob/master/spec/Candid.md I would say that this should not hold fail. And we should add a test case for that.

Also, the record-extension rules only apply to fields of type `opt empty <: t` (i.e. `opt …` and `reserved`).

**Comment by crusso** [comment]
Ok, so the error message is misleading and should omit the "... or null type".

**Comment by nomeata** [comment]
Ah, yes.

**Comment by chenyan-dfinity** [comment]
Yeah, the error message is wrong.
